In [1]:
!pip install numpy

In [8]:
import numpy as np

In [15]:
#1d Array
a=np.array([1,2,3,4,5])
#2d Array
b=np.array([[1,2,3,],
            [4,5,6]
            ])

In [18]:
print("1D Array: ",a)
print("2D Array:\n",b)

1D Array:  [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [27]:
#Arithmetic Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([7,8,9,13,11])

#Addition
print("Addition: ", arr1+arr2)
#Subtraction
print("Subtraction: ", arr2-arr1)
#Multiplication
print("Multiplication: ", arr1*arr2)
#Division
print("Division: ", arr1/arr2)
#FloorDivision
print("Floor Division: ", arr1//2)
#Modulus Division
print("Modulus Division: ", arr2%2)

Addition:  [ 8 10 12 17 16]
Subtraction:  [6 6 6 9 6]
Multiplication:  [ 7 16 27 52 55]
Division:  [0.14285714 0.25       0.33333333 0.30769231 0.45454545]
Floor Division:  [0 1 1 2 2]
Modulus Division:  [1 0 1 1 1]


In [31]:
#  Maximum, Minimum, Mean, and Sum of an array
print(arr1.max())
print(arr1.min())
print(arr1.mean())
print(arr1.sum())


5
1
3.0
15


In [44]:
#Reshape array
print("1D array:\n",arr1.reshape([5,1]))
#2D array
print("2D array: ",b.reshape([1,6]))

1D array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
2D array:  [[1 2 3 4 5 6]]


In [56]:
#Indexing and Slicing
indxArr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

#print 50 
print(indxArr[1,1])
#print 80
print(indxArr[2,1])
#print 2nd row
print(indxArr[1])
#print 3rd coloumn 
print(indxArr[:,2])


50
80
[40 50 60]
[30 60 90]
